version: 2.1
orbs:
  python: circleci/python@0.3.0
workflows:
  main:
    jobs:
      - test
      - build

jobs:
  test:
    executor:
      name: 'python/default'
      tag: '3.6'
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/test:
          pytest: true
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Build project scripts
          command: |
            sh build.sh
      - store_artifacts:
          path: /tmp/dist
