version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-2.7
      - test-3.3
      - test-3.4
      - test-3.5
      - test-3.6
jobs:
  test-3.3: &test-template
    docker:
      - image: circleci/python:3.3
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-{{ arch }}-{{ .Branch }}-{{ .Environment.PYTHON_VERSION }}-{{ checksum "requirements-test.txt" }}
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements-test.txt
      - save_cache:
          paths:
            - ./venv
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ .Environment.PYTHON_VERSION }}-{{ checksum "requirements-test.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: venv/bin/nose2
  test-3.4:
    <<: *test-template
    docker:
      - image: circleci/python:3.4
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
  test-2.7:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies from requirements-test + mock
      - restore_cache:
          keys:
            - dependencies-{{ arch }}-{{ .Branch }}-{{ .Environment.PYTHON_VERSION }}-{{ checksum "requirements-test.txt" }}
      - run:
          name: install dependencies
          command: |
            [ -d venv ] || virtualenv venv
            . venv/bin/activate
            pip install -r requirements-test.txt
            pip install mock==2.0.0
      - save_cache:
          paths:
            - ./venv
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ .Environment.PYTHON_VERSION }}-{{ checksum "requirements-test.txt" }}
      # run tests!
      - run:
          name: run tests
          command: venv/bin/nose2
