version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: circleci/python:3.3

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install tox
        
      # run tests!
      - run:
          name: run tests
          command: venv/bin/tox
